version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: weather_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - weather_net

  frontend:
    build:
      context: ./frontend
    container_name: weather_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - weather_net

networks:
  weather_net:
    driver: bridge
